apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: ProfileName
    pluginConfig:
    - name: "HighNodeUtilization"
      args:
        useActualUsage: true  #use actual usage or requests
        thresholds:
          "cpu" : 20
          "memory": 20
          "pods": 20
        numberOfNodes: 3
    plugins:
      balance:
        enabled:
          - "HighNodeUtilization"